CREATE TABLE PASSENGER (PASSENGER_ID NUMBER, 
                FIRST_NAME      VARCHAR(32)	NOT NULL, 
                MIDDLE_NAME     VARCHAR(32),
                LAST_NAME       VARCHAR(32) NOT NULL, 
                DOB 			DATE 	    NOT NULL,
                AGE 			NUMBER 	    NOT NULL, 
                GENDER 		VARCHAR(32)     NOT NULL, 
                PASSENGER_TYPE 	VARCHAR(32),
PRIMARY KEY(PASSENGER_ID));


CREATE TABLE PADDRESS_DETAILS (PASSENGER_ID	NUMBER	        NOT NULL, 
                        EMAIL        		VARCHAR(32)	    NOT NULL,
                        PHONE		      	VARCHAR(32) 	NOT NULL,
                        COUNTRY             VARCHAR(32)  	NOT NULL, 
 		                STATE			    VARCHAR(32),
                        CITY 			    VARCHAR(32) 	NOT NULL, 
                        ZIP_CODE 		    VARCHAR(32) 	NOT NULL, 
FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE);


CREATE TABLE VACCINATION_DETAILS (VACCIN_ID		NUMBER, 
                        PASSENGER_ID        	NUMBER	        NOT NULL,
                        VACCIN_NAME	      	    VARCHAR(32) 	NOT NULL,
                        VACCIN_STATUS          	VARCHAR(32)  	NOT NULL, 
PRIMARY KEY(VACCIN_ID), 
FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE);


CREATE TABLE TRAVEL_AGENCY (TRAVELAGENCY_ID		NUMBER, 
                    AGENCY_NAME           		VARCHAR(32)  	NOT NULL,
                    AGENCY_PHONE      		    VARCHAR(32) 	NOT NULL,
                    AGENCY_ADDRESS		        VARCHAR(50)  	NOT NULL,
                    AGENCY_DISCODE        		VARCHAR(32)	    NOT NULL UNIQUE,
                    AGENCY_DISAMOUNT		    NUMBER	        NOT NULL, 
PRIMARY KEY(TRAVELAGENCY_ID));


CREATE TABLE TRAVELAGENCY_PASSENGERS (TPASSENGER_ID		NUMBER	NOT NULL,
						TRAVELAGENCY_ID		            NUMBER	NOT NULL,
FOREIGN KEY(TPASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE,
FOREIGN KEY(TRAVELAGENCY_ID) REFERENCES TRAVEL_AGENCY(TRAVELAGENCY_ID) ON DELETE CASCADE);


CREATE TABLE MILITARY_PASSENGER (MPASSENGER_ID		NUMBER,
                                TRAVELAGENCY_ID		NUMBER	    NOT NULL,
                                MILITARYDISCOUNT_CODE	NUMBER	NOT NULL,
                                MILITARYDISCOUNT_AMT	NUMBER	NOT NULL,
FOREIGN KEY(MPASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE,
FOREIGN KEY(TRAVELAGENCY_ID) REFERENCES TRAVEL_AGENCY(TRAVELAGENCY_ID) ON DELETE CASCADE);


CREATE TABLE FREQUENT_PASSENGER(FPASSENGER_ID	NUMBER,
                            FPASSENGER_MILEAGE	NUMBER	NOT NULL,
                            FREQFLYCOUNT		NUMBER	NOT NULL,
                            MILEAGEEXPDATE		DATE,
                            MILEAGEBALANCE		NUMBER,
PRIMARY KEY(FPASSENGER_ID),
FOREIGN KEY(FPASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE);

CREATE TABLE CREDITCARD_DETAILS(CREDITCARDNUM	NUMBER,
                                MERCHANT_NAME	VARCHAR(32)		NOT NULL,
                                EXPDATE		    DATE			NOT NULL,
PRIMARY KEY(CREDITCARDNUM));


CREATE TABLE PCREDITCARD_DETAILS(CREDITCARDNUM	NUMBER	NOT NULL,
                                CPASSENGER_ID	NUMBER	NOT NULL,
FOREIGN KEY(CREDITCARDNUM) REFERENCES CREDITCARD_DETAILS(CREDITCARDNUM),
FOREIGN KEY(CPASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE);


CREATE TABLE TRANSACTIONS(TRANS_ID		NUMBER,
                        TOTAL_AMOUNT	NUMBER	NOT NULL,
                        CHARGES		    NUMBER	NOT NULL,
                        DISCOUNT		NUMBER,	
PRIMARY KEY(TRANS_ID));


CREATE TABLE PASSENGER_TRANSACTIONS(TRANS_ID	NUMBER,
                                TPASSENGER_ID 	NUMBER,
                                FLIGHT_NUMBER	NUMBER,
                                DEPARTURE_DATE	DATE,
                                BOOKING_DATE	DATE,
PRIMARY KEY(TRANS_ID),
FOREIGN KEY(TPASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE);


CREATE TABLE AIRLINES(AIRLINE_CODE		VARCHAR(32),
				    AIRLINE_NAME		VARCHAR(50)		NOT NULL,
                    HEAD_ADDRESS	    VARCHAR(100)	NOT NULL,
PRIMARY KEY(AIRLINE_CODE));


CREATE TABLE AIRPORT(AIRPORT_CODE	VARCHAR(32),
                AIRPORT_NAME		VARCHAR(50)		NOT NULL,
                STATE			    VARCHAR(30)		NOT NULL,
                CITY			    VARCHAR(30)		NOT NULL,
PRIMARY KEY(AIRPORT_CODE));


--ALTER TABLE FLIGHTS MODIFY FLIGHT_NUMBER VARCHAR(10);


CREATE TABLE FLIGHTS(FLIGHT_NUMBER	VARCHAR(10),
                AIRLINE_CODE		VARCHAR(32)	    NOT NULL,
                DESTINATION		    VARCHAR(32)		NOT NULL,
                SEAT_CAPACITY	    NUMBER		    NOT NULL,
                FLIGHT_TYPE		    VARCHAR(32)		NOT NULL,
PRIMARY KEY(FLIGHT_NUMBER),
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE) ON DELETE CASCADE);


CREATE TABLE FLIGHT_DESTINATION_AIRPORT(FLIGHT_NUMBER	VARCHAR(10)	    NOT NULL,
                                    AIRPORT_CODE		VARCHAR(32)	NOT NULL,	
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHTS(FLIGHT_NUMBER) ON DELETE CASCADE,
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE) ON DELETE CASCADE);


CREATE TABLE FLIGHT_ARRIVAL_AIRPORT(FLIGHT_NUMBER	VARCHAR(10)	    NOT NULL,
                                AIRPORT_CODE		VARCHAR(15)	NOT NULL,
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHTS(FLIGHT_NUMBER) ON DELETE CASCADE,
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE) ON DELETE CASCADE);


CREATE TABLE DISCOUNTS(AIRLINE_CODE	VARCHAR(15)	NOT NULL,
			        FLIGHT_NUMBER	VARCHAR(10)	    NOT NULL,
			        DISCOUNT		NUMBER	    DEFAULT 1000,
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE) ON DELETE CASCADE,
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHTS(FLIGHT_NUMBER) ON DELETE CASCADE); 


CREATE TABLE FLIGHT_TIMINGS(FLIGHT_NUMBER	VARCHAR(10),
				            FLIGHT_TIME		TIMESTAMP	NOT NULL,
			 	            FLIGHT_DATE		DATE		NOT NULL,
				            ARRIVAL_TIME	TIMESTAMP	NOT NULL,
				            DEPARTURE_TIME	TIMESTAMP	NOT NULL,
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHTS(FLIGHT_NUMBER) ON DELETE CASCADE);


CREATE TABLE PRICE_DETAILS(AIRLINE_CODE 	VARCHAR(15)	NOT NULL,
				FLIGHT_NUMBER	VARCHAR(10)	NOT NULL,
				CLASS1			NUMBER	NOT NULL,
				CLASS2			NUMBER	NOT NULL,
				CLASS3			NUMBER	NOT NULL,
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHTS(FLIGHT_NUMBER) ON DELETE CASCADE,
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE) ON DELETE CASCADE);


CREATE TABLE INSURANCE(INSURANCE_ID	NUMBER PRIMARY KEY,
			IPASSENGER_ID			NUMBER,
			INSURANCE_AMT		    NUMBER	NOT NULL,
			INSURANCEDATE	        DATE	NOT NULL,
			INSURANCEEXPDATE	    DATE	NOT NULL,
FOREIGN KEY (IPASSENGER_ID) REFERENCES PASSENGER (PASSENGER_ID) ON DELETE CASCADE);  


CREATE TABLE FOOD_PRICE(FOOD_TYPEID	NUMBER PRIMARY KEY,
			FCLASS1_PRICE	NUMBER	NOT NULL,
			FCLASS2_PRICE	NUMBER	NOT NULL,
		    FCLASS3_PRICE	NUMBER	NOT NULL);


CREATE TABLE RESERVATION(RESERVATION_ID	NUMBER PRIMARY KEY,
			FLIGHT_NUMBER	VARCHAR(15),
			PASSENGER_ID	NUMBER,
			TARVELCLASS_ID	NUMBER	NOT NULL,
			COST			NUMBER	NOT NULL,
			SEAT_NUMBER		NUMBER	NOT NULL,
			INSURANCE_ID	NUMBER,
			LUGGAGE_ID		NUMBER	UNIQUE,
			FOOD_ID		    NUMBER 	UNIQUE,
			RESERVATION_DATE DATE NOT NULL,
FOREIGN KEY (FLIGHT_NUMBER) REFERENCES FLIGHTS (FLIGHT_NUMBER) ON DELETE CASCADE,
FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (PASSENGER_ID) ON DELETE CASCADE,
FOREIGN KEY (INSURANCE_ID) REFERENCES INSURANCE (INSURANCE_ID) ON DELETE CASCADE);


CREATE TABLE RESERVATION_STATUS(RESERVATION_ID		NUMBER NOT NULL,
				            RESERVATION_STATUS		VARCHAR(32)	NOT NULL,
FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION (RESERVATION_ID) ON DELETE CASCADE);


CREATE TABLE FOOD(FOOD_ID		NUMBER PRIMARY KEY,
		        RESERVATION_ID	NUMBER,
		        FOOD_TYPEID		NUMBER,
		        FOOD_CLASS		NUMBER	NOT NULL,
FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION(RESERVATION_ID) ON DELETE CASCADE,
FOREIGN KEY(FOOD_TYPEID) REFERENCES FOOD_PRICE(FOOD_TYPEID) ON DELETE CASCADE);


CREATE TABLE LUGGAGE_DETAILS(RESERVATION_ID	NUMBER,
				LUGGAGE_ID		NUMBER,
				LUGGAGE_WEIGHT	NUMBER	NOT NULL,
				LPRICE			NUMBER	NOT NULL,
FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION (RESERVATION_ID) ON DELETE CASCADE);