CREATE OR REPLACE PROCEDURE SHOW_PASSENGERDETAILS
IS
CURSOR PASS IS SELECT * FROM PASSENGER;
GEN VARCHAR(10);
BEGIN
FOR C_PASS IN PASS LOOP
IF(C_PASS.GENDER = 'M') THEN
    GEN := 'MALE';
ELSE
  GEN := 'FEMALE';
END IF;
DBMS_OUTPUT.PUT_LINE('  '||UPPER(C_PASS.FIRST_NAME)||' '||UPPER(C_PASS.LAST_NAME)||'`S'||' BIRTHDAY IS '||C_PASS.DOB||' AND '||C_PASS.AGE||' YEARS OLD '||' AND GENDER IS '||GEN);
DBMS_OUTPUT.PUT_LINE('  ');
END LOOP;
END;
/

EXECUTE SHOW_PASSENGERDETAILS();

