CREATE SEQUENCE PASS_SEQ
    INCREMENT BY 1
    START WITH 1001
    ORDER;


CREATE SEQUENCE PADD_SEQ
    INCREMENT BY 1
    START WITH 1003
    ORDER;


SELECT PADD_SEQ.NEXTVAL FROM DUAL;


DROP SEQUENCE PASS_SEQ;
DROP SEQUENCE PADD_SEQ;