CREATE TABLE PASSENGER (PASSENGER_ID	NUMBER, 
FIRST_NAME         	VARCHAR(32)	NOT NULL, 
MIDDLE_NAME      	VARCHAR(32),
LAST_NAME           	VARCHAR(32)  	NOT NULL, 
DOB 			DATE 		NOT NULL,
AGE 			NUMBER 	NOT NULL, 
GENDER 		VARCHAR(32) 	NOT NULL, 
PASSENGER_TYPE 	VARCHAR(32),
PRIMARY KEY(PASSENGER_ID) )

