CREATE OR REPLACE FUNCTION COUNT_FEMALE_PASSENGER
RETURN VARCHAR
IS
FEMALE_COUNT NUMBER := 0;
BEGIN
SELECT COUNT(1) INTO FEMALE_COUNT FROM AIRLINE WHERE GENDER = 'Female';
RETURN 'TOTAL FEMALE PASSENGERS '||FEMALE_COUNT;
END;
/