

--1. TOTAL NO OF PASSENGERS
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE TOTAL_PASSENGERS
IS
TOTAL_COUNT NUMBER;
BEGIN
SELECT COUNT(PASSENGER_ID) INTO TOTAL_COUNT FROM PASSENGER;
DBMS_OUTPUT.PUT_LINE('TOTAL PASSENGERS'||TOTAL_COUNT);
END;
/

BEGIN
TOTAL_PASSENGERS();
END;
/


--COUNT NO OF PASSENGERS BASED ON THE GENDER PASSED
CREATE OR REPLACE PROCEDURE TOTAL_PASSENGERS_OF_GENDER(GENDR IN CHAR)
AS
TOTAL_COUNT NUMBER;
BEGIN
SELECT COUNT(*) INTO TOTAL_COUNT FROM PASSENGER WHERE GENDER=GENDR ;
DBMS_OUTPUT.PUT_LINE('TOTAL PASSENGERS '||TOTAL_COUNT);
END;
/

BEGIN
TOTAL_PASSENGERS_OF_GENDER('Male');
--TOTAL_PASSENGERS_OF_GENDER('Female');
END;
/

-->Airline details
CREATE OR REPLACE PROCEDURE AIRLINE_DETAILS
IS
BEGIN
  FOR I IN (SELECT AIRLINE_NAME,HEAD_ADDRESS FROM AIRLINES)
  LOOP 
    DBMS_OUTPUT.PUT_LINE(I.AIRLINE_NAME||' '||I.HEAD_ADDRESS); 
  END LOOP;  
END;
/

BEGIN
    AIRLINE_DETAILS();
END;

--DETAILS OF A PARTICULAR AIRLINE
CREATE OR REPLACE PROCEDURE AIRLINE_DETAILS(AIRLINE IN CHAR)
IS
BEGIN
  FOR I IN (SELECT AIRLINE_NAME,HEAD_ADDRESS FROM AIRLINES WHERE AIRLINE_NAME=AIRLINE)
  LOOP 
    DBMS_OUTPUT.PUT_LINE(I.AIRLINE_NAME||' '||I.HEAD_ADDRESS); 
  END LOOP;  
END;
/

BEGIN
    AIRLINE_DETAILS('DECCAN_AIRWAYS');
END;

-- TO COUNT TOTAL NO OF RESERVATIONS A PARTICULAR PASSENGER IS DONE WITH IN THE MONTH
CREATE OR REPLACE PROCEDURE CNT_RESERVATIONS(PASSENERID IN NUMBER)
IS
COUNTR NUMBER;
BEGIN
 SELECT COUNT(RESERVATIONID) INTO COUNTR FROM RESERVATION WHERE PASSENGERID=PASSENGERID AND RESERVATIONDATE>'15-FEB-2022' AND RESERVATIONDATE<'15-MAR-2022';
  
    DBMS_OUTPUT.PUT_LINE(COUNTR);  
END;
/

BEGIN
    CNT_RESERVATIONS(67543);
END;

--DETAILS OF THE FLIGHT BASED ON THE TYPE OF FIGHT PASSED AS AN ARGUMENT

CREATE OR REPLACE PROCEDURE FLIGHT_DETAILS(FTYPE IN VARCHAR)
IS
  CURSOR cur
  IS
    SELECT
      *
    FROM
      FLIGHT
    WHERE
      FLIGHT_TYPE =FTYPE;
BEGIN
  FOR I IN cur LOOP
    DBMS_OUTPUT.PUT_LINE(I.FLIGHT_NUMBER||'  '||I.DESTINATION||'   '||I.SEAT_CAPACITY);
  END LOOP;
END;
/

DECLARE
I CHAR(10);
BEGIN
I:='&I';    
FLIGHT_DETAILS(I);
END;
/