-- create table std(ROLLNO VARCHAR(2),NAME CHAR(10),AGE NUMBER(2));

-- drop table std;

CREATE TABLE AIRLINES(AIRLINE_CODE VARCHAR(20) PRIMARY KEY,
HEAD_ADDRESS VARCHAR(100) NOT NULL,AIRLINE_NAME VARCHAR(30) NOT NULL);

CREATE TABLE AIRPORT(AIRPORT_CODE VARCHAR(15) PRIMARY KEY,AIRPORT_NAME VARCHAR(50) NOT NULL,
CITY VARCHAR(30) NOT NULL,STATE VARCHAR(30) NOT NULL);

-- desc AIRPORT;

CREATE TABLE PRICEDETAILS(AIRLINE_CODE VARCHAR(15) NOT NULL,FLIGHT_NUMBER NUMBER,
CLASS1 NUMBER,CLASS2 NUMBER,CLASS3 NUMBER,
PRIMARY KEY(AIRLINE_CODE,FLIGHT_NUMBER),
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));
-- desc AIRLINES;

CREATE TABLE FLIGHT(FLIGHT_NUMBER NUMBER PRIMARY KEY,
AIRLINE_CODE VARCHAR(15),DESTINATION VARCHAR(32),SEAT_CAPACITY NUMBER,FLIGHT_TYPE VARCHAR(32),
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE));

CREATE TABLE FLIGHT_DESTINATION_AIRPORT(FLIGHT_NUMBER NUMBER,AIRPORT_CODE VARCHAR(15),
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));

CREATE TABLE FLIGHT_ARRIVAL_AIRPORT(FLIGHT_NUMBER NUMBER,AIRPORT_CODE VARCHAR(15),
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));

CREATE TABLE PASSENGER(PASSENGER_ID NUMBER PRIMARY KEY,FIRSTNAME VARCHAR(32) NOT NULL,
MIDDLENAME VARCHAR(32),LASTNAME VARCHAR(32) NOT NULL,DOB DATE NOT NULL,
AGE NUMBER CHECK(LENGTH(AGE)>0),GENDER CHAR(1),PASSENGER_TYPE VARCHAR(32));

CREATE TABLE DISCOUNTS(FLIGHT_NUMBER NUMBER,AIRPORT_CODE VARCHAR(15),DISCOUNT NUMBER,
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));


CREATE TABLE TRAVEL_AGENCY(TRAVELAGENCYID NUMBER(10),
TRAVELAGENCYNAME VARCHAR2(50),AGENCYADDRESS VARCHAR2(50),
AGENCYPHONE NUMBER(10),
AGENCYADDRESS VARCHAR2(50),
AGENCYDISCOUNTCODE NUMBER(10),
AGENCYDISCOUNTAMT NUMBER);

CREATE TABLE TRAVELAGENCY_PASSENGERS(TPASSENGERID NUMBER(10) PRIMARY KEY,
TRAVELAGENCYID NUMBER(10),
FOREIGN KEY(TPASSENGERID) REFERENCES PASSENGER(PASSENGER_ID));


CREATE TABLE FREQUENT_PASSENGER(FPASSENGERID NUMBER(10) PRIMARY KEY,
FREQFLYERNAME NUMBER(10),
FREQFLYERMILEGE NUMBER,
MILEAGEBALANCE NUMBER,
MILEAGEEXPDATE DATE,
FOREIGN KEY(FPASSENGERID) REFERENCES PASSENGER(PASSENGERID));


CREATE TABLE TRAVEL_CLASS(TRAVELCLASSID NUMBER(10) PRIMARY KEY,
TRAVELCLASS CHAR(20));

-- CREATE TABLE STANDARD(SPASSENGERID NUMBER(10) PRIMARY KEY,PROMODISCOUNTCODE CHAR(10),FOREIGN KEY(SPASSENGERID) REFERENCES PASSENGER(PASSENGERID));

CREATE TABLE MILITARY_PASSENGER(MPASSENGERID NUMBER(10) PRIMARY KEY,
TRAVELAGENCYID NUMBER(10),
MILITARYBRANCH VARCHAR(30),
MILITARYDISCOUNTCODE CHAR(10),
MILITARYDISCOUNTAMT NUMBER,
FOREIGN KEY(MPASSENGERID) REFERENCES PASSENGER(PASSENGER_ID),
FOREIGN KEY(TRAVELAGENCYID) REFERENCES TRAVEL_AGENCY(TRAVELAGENCYID));

CREATE TABLE CREDITCARD_DETAILS(CREDITCARDNUM NUMBER(10) PRIMARY KEY,MERCHANTNAME VARCHAR2(30),EXPDATE DATE);

CREATE TABLE PASSENGER_CREDITCARD(CREDITCARDNUM NUMBER(15),CPASSENGER_ID NUMBER(10),
FOREIGN KEY(CREDITCARDNUM) REFERENCES CREDITCARD_DETAILS(CREDITCARDNUM),
FOREIGN KEY(CPASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID),
PRIMARY KEY(CREDITCARDNUM,CPASSENGER_ID));


CREATE TABLE RESERVATION(RESERVATIONID NUMBER(10) PRIMARY KEY,
PASSENGERID NUMBER(10),
FLIGHTNUMBER NUMBER(10),
RESERVATIONDATE DATE,
SEATNO CHAR(4),
COST NUMBER,
TRAVELCLASSID NUMBER(10),
INSURANCEID NUMBER,
LUGGAGEID NUMBER,
FOODID NUMBER,
FOREIGN KEY(PASSENGERID) REFERENCES PASSENGER(PASSENGER_ID),
FOREIGN KEY(FLIGHTNUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));



CREATE TABLE RESERVATION_STATUS(RESERVATIONID NUMBER(10) PRIMARY KEY,
RESERVATIONSTATUS VARCHAR2(20),
FOREIGN KEY(RESERVATIONID) REFERENCES RESERVATION(RESERVATIONID));

