-- create table std(ROLLNO VARCHAR(2),NAME CHAR(10),AGE NUMBER(2));

-- drop table std;
--1 TABLE NAME :AIRLINES
CREATE TABLE AIRLINES(
AIRLINE_CODE VARCHAR(20) PRIMARY KEY,
HEAD_ADDRESS VARCHAR(100) NOT NULL,
AIRLINE_NAME VARCHAR(30) NOT NULL);

--2 TABLE NAME :AIRPORT
CREATE TABLE AIRPORT(
AIRPORT_CODE VARCHAR(15) PRIMARY KEY,
AIRPORT_NAME VARCHAR(50) NOT NULL,
CITY VARCHAR(30) NOT NULL,STATE VARCHAR(30) NOT NULL);

-- desc AIRPORT;

--3 TABLE NAME :PRICEDETAILS
CREATE TABLE PRICEDETAILS(
AIRLINE_CODE VARCHAR(15) NOT NULL,FLIGHT_NUMBER NUMBER,
CLASS1 NUMBER,CLASS2 NUMBER,CLASS3 NUMBER,
PRIMARY KEY(AIRLINE_CODE,FLIGHT_NUMBER),
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));
-- desc AIRLINES;

--4 TABLE NAME :FLIGHT
CREATE TABLE FLIGHT(
FLIGHT_NUMBER NUMBER PRIMARY KEY,
AIRLINE_CODE VARCHAR(15),DESTINATION VARCHAR(32),SEAT_CAPACITY NUMBER,FLIGHT_TYPE VARCHAR(32),
FOREIGN KEY(AIRLINE_CODE) REFERENCES AIRLINES(AIRLINE_CODE));

--5  TABLE NAME : FLIGHT_DESTINATION_AIRPORT
CREATE TABLE FLIGHT_DESTINATION_AIRPORT(
FLIGHT_NUMBER NUMBER,AIRPORT_CODE VARCHAR(15),
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));

--6 TABLE NAME : FLIGHT_ARRIVAL_AIRPORT
CREATE TABLE FLIGHT_ARRIVAL_AIRPORT(
FLIGHT_NUMBER NUMBER,AIRPORT_CODE VARCHAR(15),
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));

--7 TABLE NAME : PASSENGER
CREATE TABLE PASSENGER(
PASSENGER_ID NUMBER PRIMARY KEY,
FIRSTNAME VARCHAR(32) NOT NULL,
MIDDLENAME VARCHAR(32),
LASTNAME VARCHAR(32) NOT NULL,
DOB DATE NOT NULL,
AGE NUMBER CHECK(LENGTH(AGE)>0),
GENDER CHAR(1),
PASSENGER_TYPE VARCHAR(32));


--8 TABLE NAME : PASSENGER_DETAILS
CREATE TABLE PADDRESS_DETAILS ( 
PASSENGER_ID NUMBER NOT NULL, 
EMAIL VARCHAR(32) NOT NULL,
PHONE VARCHAR(32) NOT NULL,
COUNTRY VARCHAR(32) NOT NULL, 
STATE VARCHAR(32) NOT NULL,
CITY VARCHAR(32) NOT NULL, 
ZIP_CODE VARCHAR(32) NOT NULL, 
FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE);

--9 TABLE NAME : VACCINATION_DETAILS

CREATE TABLE VACCINATION_DETAILS (
VACCIN_ID NUMBER PRIMARY KEY, 
PASSENGER_ID NUMBER NOT NULL,
VACCIN_NAME VARCHAR(32) NOT NULL,
VACCIN_STATUS VARCHAR(32) NOT NULL, 
FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE);


--10 TABLE NAME : DISCOUNTS
CREATE TABLE DISCOUNTS(
FLIGHT_NUMBER NUMBER,
AIRPORT_CODE VARCHAR(15),
DISCOUNT NUMBER,
FOREIGN KEY(AIRPORT_CODE) REFERENCES AIRPORT(AIRPORT_CODE),
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));


--11 TABLE NAME : TRAVREL_AGENCY
CREATE TABLE TRAVEL_AGENCY(TRAVELAGENCYID NUMBER(10),
TRAVELAGENCYNAME VARCHAR2(50),AGENCYADDRESS VARCHAR2(50),
AGENCYPHONE NUMBER(10),
AGENCYADDRESS VARCHAR2(50),
AGENCYDISCOUNTCODE NUMBER(10),
AGENCYDISCOUNTAMT NUMBER);

--12 TABLE NAME : TRAVELAGENCY_PASSENGERS
CREATE TABLE TRAVELAGENCY_PASSENGERS(
TPASSENGERID NUMBER(10) PRIMARY KEY,
TRAVELAGENCYID NUMBER(10),
FOREIGN KEY(TPASSENGERID) REFERENCES PASSENGER(PASSENGER_ID));


--13 TABLE NAME : FREQUENT_PASSENGER
CREATE TABLE FREQUENT_PASSENGER(
FPASSENGERID NUMBER(10) PRIMARY KEY,
FREQFLYERNAME NUMBER(10),
FREQFLYERMILEGE NUMBER,
MILEAGEBALANCE NUMBER,
MILEAGEEXPDATE DATE,
FOREIGN KEY(FPASSENGERID) REFERENCES PASSENGER(PASSENGERID));

--14 TABLE NAME : TRAVEL_CLASS
CREATE TABLE TRAVEL_CLASS(
TRAVELCLASSID NUMBER(10) PRIMARY KEY,
TRAVELCLASS CHAR(20));

-- CREATE TABLE STANDARD(SPASSENGERID NUMBER(10) PRIMARY KEY,PROMODISCOUNTCODE CHAR(10),FOREIGN KEY(SPASSENGERID) REFERENCES PASSENGER(PASSENGERID));

--15 TABLE NAME : MILITARY_PASSENGER
CREATE TABLE MILITARY_PASSENGER(
MPASSENGERID NUMBER(10) PRIMARY KEY,
TRAVELAGENCYID NUMBER(10),
MILITARYBRANCH VARCHAR(30),
MILITARYDISCOUNTCODE CHAR(10),
MILITARYDISCOUNTAMT NUMBER,
FOREIGN KEY(MPASSENGERID) REFERENCES PASSENGER(PASSENGER_ID),
FOREIGN KEY(TRAVELAGENCYID) REFERENCES TRAVEL_AGENCY(TRAVELAGENCYID));

--16 TABLE NAME : CREDITCARD_DETAILS
CREATE TABLE CREDITCARD_DETAILS(CREDITCARDNUM NUMBER(10) PRIMARY KEY,
MERCHANTNAME VARCHAR2(30),
EXPDATE DATE);

--17 TABLE NAME : PASSENGER_CREDITCARD
CREATE TABLE PASSENGER_CREDITCARD(CREDITCARDNUM NUMBER(15),CPASSENGER_ID NUMBER(10),
FOREIGN KEY(CREDITCARDNUM) REFERENCES CREDITCARD_DETAILS(CREDITCARDNUM),
FOREIGN KEY(CPASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID),
PRIMARY KEY(CREDITCARDNUM,CPASSENGER_ID));


--18 TABLE NAME : TRANSACTIONS
CREATE TABLE TRANSACTIONS( 
TRANS_ID NUMBER PRIMARY KEY,
TOTAL_AMOUNT NUMBER	NOT NULL,
CHARGES NUMBER NOT NULL,
DISCOUNT NUMBER,	
);

--19 TABLE NAME : PASSENGER_TRANSACTIONS
CREATE TABLE PASSENGER_TRANSACTIONS(
TRANS_ID	    NUMBER PRIMARY KEY,
TPASSENGER_ID 	NUMBER,
FLIGHT_NUMBER	VARCHAR2(5),
DEPARTURE_DATE	DATE,
BOOKING_DATE	DATE,
PRIMARY KEY(TRANS_ID),
FOREIGN KEY(TPASSENGER_ID) REFERENCES PASSENGER(PASSENGER_ID) ON DELETE CASCADE);

--20 TABLE NAME : FLIGHT_TIMINGS
CREATE TABLE FLIGHT_TIMINGS(
FLIGHT_NUMBER VARCHAR2(5),
FLIGHT_TIME	TIMESTAMP NOT NULL,
FLIGHT_DATE	DATE NOT NULL,
ARRIVAL_TIME TIMESTAMP NOT NULL,
DEPARTURE_TIME TIMESTAMP NOT NULL,
FOREIGN KEY(FLIGHT_NUMBER) REFERENCES FLIGHTS(FLIGHT_NUMBER) ON DELETE CASCADE);
				
--21 TABLE NAME : INSURANCE
CREATE TABLE INSURANCE( 
INSURANCE_ID NUMBER PRIMARY KEY,
IPASSENGER_ID NUMBER,
INSURANCE_AMT NUMBER NOT NULL,
INSURANCEDATE DATE NOT NULL,
INSURANCEEXPDATE DATE NOT NULL,
FOREIGN KEY (IPASSENGER_ID) REFERENCES PASSENGER (PASSENGER_ID) ON DELETE CASCADE); 

--22 TABLE NAME : RESERVATION
CREATE TABLE RESERVATION(
RESERVATIONID NUMBER(10) PRIMARY KEY,
PASSENGERID NUMBER(10),
FLIGHTNUMBER NUMBER(10),
RESERVATIONDATE DATE,
SEATNO CHAR(4),
COST NUMBER,
TRAVELCLASSID NUMBER(10),
INSURANCEID NUMBER,
LUGGAGEID NUMBER,
FOODID NUMBER,
FOREIGN KEY(PASSENGERID) REFERENCES PASSENGER(PASSENGER_ID),
FOREIGN KEY(FLIGHTNUMBER) REFERENCES FLIGHT(FLIGHT_NUMBER));


--23 TABLE NAME : RESERVATION_STATUS
CREATE TABLE RESERVATION_STATUS(
RESERVATIONID NUMBER(10) PRIMARY KEY,
RESERVATIONSTATUS VARCHAR2(20),
FOREIGN KEY(RESERVATIONID) REFERENCES RESERVATION(RESERVATIONID));

--24 TABLE NAME : FOOD_PRICE
CREATE TABLE FOOD_PRICE(
FOOD_TYPEID	NUMBER,
FCLASS1_PRICE NUMBER NOT NULL,
FCLASS2_PRICE NUMBER NOT NULL,
FCLASS3_PRICE NUMBER NOT NULL,
PRIMARY KEY (FOOD_TYPEID));

-- 25 TABLE NAME : FOOD
CREATE TABLE FOOD( 
FOOD_ID	NUMBER,
RESERVATION_ID	NUMBER,
FOOD_TYPEID		NUMBER,
FOOD_CLASS		NUMBER	NOT NULL,
PRIMARY KEY (FOOD_ID),
FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION (RESERVATION_ID) ON DELETE CASCADE,
FOREIGN KEY(FOOD_TYPEID) REFERENCES FOOD_PRICE(FOOD_TYPEID) ON DELETE CASCADE);

-- 25 TABLE NAME : LUGGAGE_DETAILS
CREATE TABLE LUGGAGE_DETAILS(   
RESERVATION_ID NUMBER,
LUGGAGE_ID NUMBER,
LUGGAGE_WEIGHT NUMBER NOT NULL,
LPRICE NUMBER NOT NULL,
PRIMARY KEY (LUGGAGE_ID),
FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION (RESERVATION_ID) ON DELETE CASCADE);

--26. TABLE NAME: COST_DETAILS
	
CREATE TABLE COST_DETAILS( 
RESERVATION_ID	NUMBER,
LUGGAGE_ID NUMBER,
FOOD_ID	 NUMBER,
INSURANCE_ID NUMBER,	
FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATION (RESERVATION_ID) ON DELETE CASCADE,
FOREIGN KEY (LUGGAGE_ID) REFERENCES LUGGAGE_DETAILS (LUGGAGE_ID) ON DELETE CASCADE,
FOREIGN KEY (FOOD_ID) REFERENCES FOOD (FOOD_ID) ON DELETE CASCADE,
FOREIGN KEY (INSURANCE_ID) REFERENCES INSURANCE (INSURANCE_ID) ON DELETE CASCADE);                    
