--1. Find how many Percentages of male Passengers book an air ticket?

CREATE OR REPLACE PROCEDURE MALE_PASS_PERCENTAGE
AS
    TOTAL_GENDER NUMBER;
    TOTAL_MALE NUMBER;
    PERCENTAGE NUMBER;
BEGIN
    SELECT COUNT(GENDER) INTO TOTAL_GENDER
    FROM AIRLINE;
    SELECT COUNT(*) INTO TOTAL_MALE
    FROM AIRLINE
    WHERE GENDER = 'Male';
    PERCENTAGE := ROUND(TOTAL_MALE/TOTAL_GENDER*100);
    DBMS_OUTPUT.PUT_LINE('TOTAL BOOKED MALE PASSENGERS IS :'|| PERCENTAGE || '%');
END;
/

BEGIN 
    MALE_PASS_PERCENTAGE();
END;

-- END OF 1 

--2. Find how many Percentages of female Passengers book an air ticket?

CREATE OR REPLACE PROCEDURE FEMALE_PASS_PERCENTAGE
AS
    TOTAL_GENDER NUMBER;
    TOTAL_FEMALE NUMBER;
    PERCENTAGE_FEMALE NUMBER;
BEGIN
    SELECT COUNT(*) INTO TOTAL_GENDER
    FROM AIRLINE;
    SELECT COUNT(*) INTO TOTAL_FEMALE
    FROM AIRLINE
    WHERE GENDER = 'Female';
    PERCENTAGE_FEMALE := ROUND(TOTAL_FEMALE/TOTAL_GENDER*100);
    DBMS_OUTPUT.PUT_LINE('TOTAL BOOKED FEAMLE PASSENGERS IS :' ||  PERCENTAGE_FEMALE || '%');
END;
/

BEGIN
    FEMALE_PASS_PERCENTAGE();
END;
/

--END OF 2

--3. Find how many Percentages of Passengers book a business class Ticket?

CREATE OR REPLACE PROCEDURE BUSINESS_CLASS_PASS_PERCENTAGE
AS
    TOTAL_PASSENGER NUMBER;
    TOTAL_BUSINESS NUMBER;
    PERCENTAGE_BUSINESS NUMBER;
BEGIN
    SELECT COUNT(CLASS) INTO TOTAL_PASSENGER
    FROM AIRLINE;
    SELECT COUNT(*) INTO TOTAL_BUSINESS
    FROM AIRLINE
    WHERE CLASS = 'Business';
    PERCENTAGE_BUSINESS := ROUND(TOTAL_BUSINESS/TOTAL_PASSENGER*100);
    DBMS_OUTPUT.PUT_LINE('TOTAL BUSINESS CLASS BOOKED PASSENGERS :' ||PERCENTAGE_BUSINESS||'%');
END;
/

BEGIN
    BUSINESS_CLASS_PASS_PERCENTAGE();
END;
/

--END OF 3

-- 4. Find how many Percentages of passengers book an Eco class Ticket?

CREATE OR REPLACE PROCEDURE ECO_CLASS_PERCENTAGE
AS
    TOTAL_PASSENGER NUMBER;
    TOTAL_ECO NUMBER;
    PERCENTAGE_ECO NUMBER;
BEGIN
    SELECT COUNT(*) INTO TOTAL_PASSENGER
    FROM AIRLINE;
    SELECT COUNT(*) INTO TOTAL_ECO
    FROM AIRLINE
    WHERE CLASS = 'Eco';
    PERCENTAGE_ECO := ROUND(TOTAL_ECO/TOTAL_PASSENGER*100);
    DBMS_OUTPUT.PUT_LINE('THE PASSENGERS BOKKED AN ECO CLASS TICKET : ' ||PERCENTAGE_ECO||'%');
END;
/

BEGIN
    ECO_CLASS_PERCENTAGE();
END;
/

--END OF 4

--5. Find how many Percentages of male Passengers book a business class Ticket?

CREATE OR REPLACE PROCEDURE MALE_BUSINESS_CLASS_PERCENTAGE
AS
    TOTAL_GENDER NUMBER;
    TOTAL_MALE NUMBER;
    PERCENTAGE NUMBER;
BEGIN
    SELECT COUNT(GENDER) INTO TOTAL_GENDER
    FROM AIRLINE;
    SELECT COUNT(*) INTO TOTAL_MALE
    FROM AIRLINE
    WHERE GENDER = 'Male' AND CLASS = 'Business';
    PERCENTAGE := ROUND(TOTAL_MALE/TOTAL_GENDER*100);
    DBMS_OUTPUT.PUT_LINE('TOTAL MALES BOOKED BUSINESS CLASS TICKET : '||PERCENTAGE ||'%');
END;
/
BEGIN 
    MALE_BUSINESS_CLASS_PERCENTAGE();
END; 

--END 0F 5
