CREATE OR REPLACE PROCEDURE SHOW_PASSENGERDETAILS
IS
  CURSOR PASS 
  IS 
    SELECT 
      * 
    FROM 
      PASSENGER;
  GEN VARCHAR(10);
BEGIN
  FOR C_PASS IN PASS LOOP
    IF(C_PASS.GENDER = 'M') THEN
      GEN := 'MALE';
    ELSE
      GEN := 'FEMALE';
    END IF;
      DBMS_OUTPUT.PUT_LINE('  '||UPPER(C_PASS.FIRST_NAME)||' '||UPPER(C_PASS.LAST_NAME)||'`S'||' BIRTHDAY IS '||C_PASS.DOB||' AND '||C_PASS.AGE||' YEARS OLD '||' AND GENDER IS '||GEN);
      DBMS_OUTPUT.PUT_LINE('  ');
    END LOOP;
END;
/

SET SERVEROUTPUT ON;
BEGIN
  SHOW_PASSENGERDETAILS();
END;
/
SELECT * FROM PASSENGER;

-->Airline details
CREATE OR REPLACE PROCEDURE AIRLINE
IS
TYPE VARCHAR_TYPE IS TABLE OF VARCHAR(100);
A_AIRLINENAME VARCHAR_TYPE;
HEAD_ADD VARCHAR_TYPE;
BEGIN
  SELECT
    AIRLINE_NAME,HEAD_ADDRESS
  BULK COLLECT   
  INTO
    A_AIRLINENAME,HEAD_ADD  
  FROM
    AIRLINES;
  FOR I IN 1..A_AIRLINENAME.COUNT
  LOOP 
    DBMS_OUTPUT.PUT_LINE(A_AIRLINENAME(I)||' '||HEAD_ADD(I)); 
  END LOOP;  
END;


BEGIN
    AIRLINE();
END;


CREATE OR REPLACE PROCEDURE DOMSTIC_FLIGINTS
IS
  CURSOR cur
  IS
    SELECT
      *
    FROM
      FLIGHTS
    WHERE
      FLIGHT_TYPE ='Domestic';
BEGIN
  FOR I IN cur LOOP
    DBMS_OUTPUT.PUT_LINE(I.FLIGHT_NUMBER||'  '||I.DESTINATION||'   '||I.SEAT_CAPACITY);
  END LOOP;
END;
/

EXEC DOMSTIC_FLIGINTS();

CREATE OR REPLACE PROCEDURE INTERNATIONAL_FLIGINTS
IS
  CURSOR cur
  IS
    SELECT
      *
    FROM
      FLIGHTS
    WHERE
      FLIGHT_TYPE ='International';
BEGIN
  FOR I IN cur LOOP
    DBMS_OUTPUT.PUT_LINE(I.FLIGHT_NUMBER||'  '||I.DESTINATION||'   '||I.SEAT_CAPACITY);
  END LOOP;
END;
/

EXEC INTERNATIONAL_FLIGINTS();