--INSERT VALUES INTO PASSENGER TABLE
BEGIN
ADD_PASSENGER('Zoya','M','Andriya',TO_DATE('04-01-1940','DD-MM-YYYY'),'F');
END;
/

--INSERT VALUES INTO PASSENGER ADDRESS TABLE
BEGIN
PASS_ADDRESS('Zoya@gmail.com',9135148762,'Singapore',NULL,'Kampong Java Teban','25527');
END;
/

--INSERT VALUES INTO PASSENGER  VACCINATION TABLE
BEGIN
ADD_VACCIN_DETAILS(59912,1020,'Sinovac','2 Dose');
END;
/

BEGIN
ADD_FLIGHT_TIMES('AI543');
END;
/

ALTER SESSION SET TIME_ZONE = 'Asia/Calcutta';

SELECT 
    TO_CHAR(CURRENT_TIMESTAMP,' DD-MON-YYYY HH12:MI PM') 
FROM 
    DUAL;

SELECT 
    TO_DATE(TO_CHAR(SYSDATE,'DD-MON-YYYY')) 
FROM 
    DUAL;

SELECT 
    * 
FROM 
    FLIGHT_TIMINGS;

SELECT 
    * 
FROM 
    FLIGHT_TIMINGS 
WHERE 
    TO_CHAR(FLIGHT_TIME,'HH12:MI:SS PM') ='09:48:18 PM';

SELECT 
    * 
FROM 
    FREQUENT_PASSENGER;

DELETE FROM FLIGHT_TIMINGS;

DELETE FROM PASSENGER;

SELECT 
    * 
FROM 
    MILITARY_PASSENGER;

SELECT 
    * 
FROM 
    PASSENGER;

SELECT 
    * 
FROM 
    TRAVELAGENCY_PASSENGERS;

SELECT 
    * 
FROM 
    VACCINATION_DETAILS;

DESC PADDRESS_DETAILS;

DELETE FROM PADDRESS_DETAILS;

SELECT 
    * 
FROM 
    INSURANCE 
WHERE 
    INSURANCEDATE = '27-JUL-2022';

ALTER TABLE MILITARY_PASSENGER MODIFY MILITARYDISCOUNT_CODE VARCHAR(15);

SELECT 
    * 
FROM 
    CREDITCARD_DETAILS;

SELECT 
    TO_CHAR(SYSDATE,'HH:MM:SS'),
    TO_CHAR(SYSDATE+INTERVAL '24' HOUR,'HH24:MI:SS AM') 
FROM 
    DUAL;			

SELECT 
    SYSDATE+INTERVAL '24' HOUR 
FROM 
    DUAL;


ALTER SESSION SET TIME_ZONE = '-2:0'; 
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY HH24:MI:SS';

SELECT CURRENT_TIMESTAMP,SESSIONTIMEZONE FROM DUAL;

SELECT SYSDATE FROM DUAL;
SELECT ROUND((SYSDATE - TO_DATE('29-11-2003','DD-MM-YYYY'))/365.25, 0) FROM DUAL;


SET SERVEROUTPUT ON;
DECLARE
AGE NUMBER ;
PASS_TYPE VARCHAR(15);
BEGIN
AGE := ROUND((SYSDATE - TO_DATE(&DOB,'DD-MM-YYYY'))/365.25, 0);
IF AGE >= 60 THEN
    PASS_TYPE := 'CITIZEN';
ELSIF AGE < 60 AND AGE >= 18 THEN
    PASS_TYPE := 'ADULT';
ELSE
    PASS_TYPE := 'CHILDREN';
END IF;
DBMS_OUTPUT.PUT_LINE(AGE||' '||PASS_TYPE);
END;


INSERT INTO PASSENGER VALUES(&P_ID,TO_CHAR(&F_NAME),TO_CHAR(&M_NAME),TO_CHAR(&L_NAME),TO_DATE(&DOB),&AGE,&GENDER,&PASSENGER_TYPE);

SELECT * FROM TAB;

SELECT TO_CHAR(TO_DATE('12-05-2022','DD-MM-YYYY')) FROM DUAL;


DECLARE
TYPE T_NAME_TYPE IS TABLE OF VARCHAR(32);
T_FNAME T_NAME_TYPE;
T_LNAME T_NAME_TYPE;

T_FIRST_LAST T_NAME_TYPE;
L_NAME VARCHAR(32);
BEGIN
SELECT FIRST_NAME,LAST_NAME BULK COLLECT INTO T_FNAME,T_LNAME FROM PASSENGER;
END;
/



