CREATE OR REPLACE FUNCTION COUNT_FEMALE_PASSENGER
RETURN VARCHAR
IS
    FEMALE_COUNT NUMBER := 0;
BEGIN
    SELECT 
        COUNT(1) 
    INTO 
        FEMALE_COUNT 
    FROM 
        PASSENGER 
    WHERE 
        GENDER = 'F';
    RETURN 'TOTAL FEMALE PASSENGERS '||FEMALE_COUNT;
END;
/


SELECT 
    COUNT_FEMALE_PASSENGER() 
FROM DUAL;

SELECT * FROM AIRLINE;

CREATE OR REPLACE FUNCTION COUNT_MALE_PASSENGER
RETURN VARCHAR
IS
    MALE_COUNT NUMBER := 0;
BEGIN
    SELECT 
        COUNT(1) 
    INTO 
        MALE_COUNT 
    FROM 
        PASSENGER 
    WHERE 
        GENDER = 'M';
    RETURN 'TOTAL MALE PASSENGERS '||MALE_COUNT;
END;
/

SELECT 
    COUNT_MALE_PASSENGER()
FROM
    DUAL;