--1. Count how many Female passengers book an air ticket
--select count(*) from airline where gender='Female';
CREATE OR REPLACE PROCEDURE FEMALEPASSENGER
AS
FCOUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO FCOUNT
    FROM AIRLINE
    WHERE GENDER = 'Female';
    DBMS_OUTPUT.PUT_LINE('NUMBER OF FEMALE PASSENGERS BOOKED THEIR TICKET: ' || FCOUNT);
END;
/
 
BEGIN
    FEMALEPASSENGER();
END;
/

-- 2. Count the passenger list class-wise?
-- select class,count(*) from airline group by class;
SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE CLASSLIST
AS
BEGIN
    FOR I IN ( SELECT  CLASS, COUNT(*) AS CLASSTOTAL
                FROM AIRLINE
                GROUP BY CLASS)
    LOOP
        DBMS_OUTPUT.PUT_LINE(I.CLASS || ' : ' || I.CLASSTOTAL);
    END LOOP;
END;
/

BEGIN
    CLASSLIST();
END;
/

--3. Display the passenger count who is all booking business Class; 
-- SELECT COUNT(*) AS BUSINESS_CLASS FROM AIRLINE WHERE CLASS='Business';
CREATE OR REPLACE PROCEDURE BUSINESS_PASSENGERS
AS
    PASS_CNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO PASS_CNT
    FROM AIRLINE
    WHERE CLASS = 'Business';
    DBMS_OUTPUT.PUT_LINE('NUMBER OF BUSINESS CLASS PASSENGERS ARE : '||PASS_CNT);
END;
/

BEGIN
    BUSINESS_PASSENGERS();
END;
/
 

--4. Count the kid passenger list? (kid = age is less than 13)
--  SELECT COUNT(*) CHILD_COUNT FROM AIRLINE WHERE AGE<13;

CREATE OR REPLACE PROCEDURE KIDS_CNT
AS
    CNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO CNT
    FROM AIRLINE
    WHERE AGE < 13;
    DBMS_OUTPUT.PUT_LINE('COUNT OF THE KID PASSENGERS : '||CNT);
END;
/

BEGIN 
    KIDS_CNT();
END;
/


-- 5. Count the passenger list of each Travel type?
-- SELECT COUNT(*),TYPE_OF_TRAVEL FROM AIRLINE GROUP BY TYPE_OF_TRAVEL;

CREATE OR REPLACE PROCEDURE TRAVEL_TYPE
AS
BEGIN
    FOR I IN (SELECT COUNT(*) AS TTYPE_COUNT, TYPE_OF_TRAVEL 
    FROM AIRLINE
    GROUP BY TYPE_OF_TRAVEL)
    LOOP
    DBMS_OUTPUT.PUT_LINE( I.TYPE_OF_TRAVEL|| ' ' || I.TTYPE_COUNT);
    END LOOP;
END;
/

BEGIN 
    TRAVEL_TYPE();
END;
/

--5 USING CURSORS
DECLARE
CURSOR C IS SELECT COUNT(*) AS TTYPE_COUNT, TYPE_OF_TRAVEL 
    FROM AIRLINE
    GROUP BY TYPE_OF_TRAVEL;
BEGIN
    FOR I IN C
    LOOP
    DBMS_OUTPUT.PUT_LINE( I.TYPE_OF_TRAVEL|| ' ' || I.TTYPE_COUNT);
    END LOOP;
END;
/




-- 6. Display the count of passengers booking eco class?

-- SELECT COUNT(*) COUNT_ECO FROM AIRLINE WHERE CLASS='Eco';
CREATE OR REPLACE PROCEDURE ECO_PASSENGER_CNT
AS
    ECO_PASSENGER NUMBER;
BEGIN
    SELECT COUNT(*) INTO ECO_PASSENGER
    FROM AIRLINE
    WHERE CLASS = 'Eco';
    DBMS_OUTPUT.PUT_LINE('THE COUNT OF ECO PASSENGERS ARE : ' ||ECO_PASSENGER);
END;
/

BEGIN
    ECO_PASSENGER_CNT();
END;
/


--7. Count the passenger list above age 16 and book a business class?
-- SELECT COUNT(*) FROM AIRLINE WHERE AGE>16 AND CLASS='Business';

CREATE OR REPLACE PROCEDURE BUSINESS_ADULT_CNT
AS
    ADULT_PASSENGER NUMBER;
BEGIN 
    SELECT COUNT(*) INTO ADULT_PASSENGER
    FROM AIRLINE
    WHERE AGE > 16 AND CLASS = 'Business';
    DBMS_OUTPUT.PUT_LINE('COUNT OF ADULT BUSINESS PASSENGERS: '||ADULT_PASSENGER);
END;
/

BEGIN 
    BUSINESS_ADULT_CNT();
END;
/

-- 8. Count the passenger list of each satisfaction? 

--SELECT SATISFACTION,COUNT(*) FROM AIRLINE GROUP BY SATISFACTION;

CREATE OR REPLACE PROCEDURE SATISFACTION_CNT
AS
BEGIN
    FOR C IN (SELECT SATISFACTION, COUNT(*) AS SATISFACTION_COUNT
                FROM AIRLINE
                GROUP BY SATISFACTION)
    LOOP
        DBMS_OUTPUT.PUT_LINE(C.SATISFACTION ||' : '|| C.SATISFACTION_COUNT);
    END LOOP;
END;
/

BEGIN
    SATISFACTION_CNT();
END;
/


-- 9. Display the customer type where gender is male and display them according to the class?
-- SELECT CUSTOMER_TYPE,CLASS FROM AIRLINE WHERE GENDER='Male' ORDER BY CLASS;

-- CREATE INDEX INDEX_AIRLINES2  ON AIRLINE(GENDER,CLASS);

CREATE OR REPLACE PROCEDURE CUSTOMER_TYPE
AS
BEGIN
    FOR I IN 
    (SELECT CUSTOMER_TYPE,CLASS         
    FROM AIRLINE
    WHERE GENDER = 'Male'
    ORDER BY CLASS)
    LOOP
      DBMS_OUTPUT.PUT_LINE(I.CUSTOMER_TYPE||'   '||I.CLASS);
    END LOOP;

END;
/

BEGIN
    CUSTOMER_TYPE();
END;

-- SELECT COUNT(ID) FROM AIRLINE WHERE AGE>16 AND CLASS='Business';


