-- PERFORMANCE BASED QUERIES SET 2

CREATE INDEX INDEX_BUSINESS_FEMALE_CNT  ON AIRLINE(GENDER,CLASS);

-- DROP INDEX INDEX_BUSINESS_FEMALE_CNT;
--COUNT TOTAL NO OF FEMALE PASSENGERS IN BUSINESS CLASS
--SELECT COUNT(GENDER) FROM AIRLINE WHERE CLASS='Business' AND GENDER='Female';
CREATE OR REPLACE PROCEDURE BSNS_FML_CNT
AS
CNT NUMBER;
BEGIN
SELECT COUNT(GENDER) INTO CNT FROM AIRLINE WHERE CLASS='Business' AND GENDER='Female';
 DBMS_OUTPUT.PUT_LINE(' TOTAL NO OF FEMALE PASSENGERS IN BUSINESS CLASS : '||CNT);
END;
/

BEGIN
    BSNS_FML_CNT();
END;
/

--2.COUNT TOTAL NO OF MALE PASSENGERS ACCORDING TO THEIR CLASS

--SELECT CLASS,COUNT(CLASS) FROM AIRLINE WHERE GENDER='Male' GROUP BY CLASS; 

CREATE OR REPLACE PROCEDURE CLASSWISE_MALE_CNT
AS
BEGIN
 FOR I IN (SELECT CLASS,COUNT(CLASS) AS CLSCNT 
           FROM AIRLINE WHERE GENDER='Male'
           GROUP BY CLASS)
 LOOP          
 DBMS_OUTPUT.PUT_LINE(I.CLASS||'  '||I.CLSCNT);
END LOOP;
END;
/

BEGIN
    CLASSWISE_MALE_CNT();
END;
/

--3. SELECT BUSINESS CLASS ADULTS
--SELECT ID FROM AIRLINE WHERE CLASS='Business' AND AGE>15;

CREATE OR REPLACE PROCEDURE BUSINESS_CLS_ADULT
AS
BEGIN
 FOR I IN (SELECT ID FROM AIRLINE
             WHERE CLASS='Business' AND AGE>15)
 LOOP          
 DBMS_OUTPUT.PUT_LINE(I.ID);
END LOOP;
END;
/

BEGIN
    BUSINESS_CLS_ADULT();
END;
/


--4.COUNT NO OF PASSENGERS IN EACH CUSTOMER_TYPE
--SELECT COUNT(ID),CUSTOMER_TYPE FROM AIRLINE GROUP BY CUSTOMER_TYPE;

CREATE OR REPLACE PROCEDURE CNT_CUSTOMER_TYPE
AS
BEGIN
 FOR I IN (SELECT COUNT(ID) AS ID,CUSTOMER_TYPE 
           FROM AIRLINE
           GROUP BY CUSTOMER_TYPE)
LOOP          
 DBMS_OUTPUT.PUT_LINE(I.ID||' '||I.CUSTOMER_TYPE);
END LOOP;
END;
/

BEGIN
    CNT_CUSTOMER_TYPE();
END;
/

--5. SELECT ALL DETAILS OF PASSENGERS WO ARE BOOKING ECO CLASS

--SELECT * FROM AIRLINE WHERE CLASS='Eco';

CREATE OR REPLACE PROCEDURE ECOCLS_DETAILS
AS
BEGIN
 FOR I IN (SELECT ID FROM AIRLINE WHERE CLASS='Eco')
LOOP          
 DBMS_OUTPUT.PUT_LINE(I.ID);
END LOOP;
END;
/

BEGIN
    ECOCLS_DETAILS();
END;
/

